In [1]:
import pandas as pd
import sqlite3

In [3]:
import os
os.listdir()

['.anaconda',
 '.conda',
 '.continuum',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.virtual_documents',
 '.vscode',
 'anaconda3',
 'apexplanet-data-analytics',
 'apexplanet-data-analytics.txt',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'Documents',
 'Downloads',
 'Favorites',
 'Links',
 'Local Settings',
 'Music',
 'My Documents',
 'NetHood',
 'Network - Shortcut.lnk',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{d7b1d167-ba51-11ef-adb3-282e89a886b7}.TM.blf',
 'NTUSER.DAT{d7b1d167-ba51-11ef-adb3-282e89a886b7}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{d7b1d167-ba51-11ef-adb3-282e89a886b7}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Superstore _cleaned.csv',
 'Task_2_SQL_Analysis.ipynb',
 'Templates',
 'Untitled Folder',
 'Videos']

In [5]:
import glob
glob.glob("*.csv")

['Superstore _cleaned.csv']

In [6]:
csv_file=glob.glob("*.csv")[0]
df=pd.read_csv(csv_file)
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,12/6/2016,16/6/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [7]:
conn=sqlite3.connect("superstore.db")

In [8]:
df.to_sql("sales",conn,if_exists="replace",index=False)

9994

In [9]:
query="""SELECT*FROM sales LIMIT 5;"""
result=pd.read_sql(query,conn)
result

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,12/6/2016,16/6/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [10]:
query="""SELECT *FROM sales WHERE sales>500 LIMIT 10;"""
result=pd.read_sql(query,conn)
result

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,2,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
1,4,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
2,8,CA-2014-115812,9/6/2014,14/6/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
3,11,CA-2014-115812,9/6/2014,14/6/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092
4,12,CA-2014-115812,9/6/2014,14/6/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002033,Technology,Phones,Konftel 250 Conference phone - Charcoal black,911.4240,4,0.20,68.3568
5,17,CA-2014-105893,11/11/2014,18/11/2014,Standard Class,PK-19075,Pete Kriz,Consumer,United States,Madison,...,53711,Central,OFF-ST-10004186,Office Supplies,Storage,"Stur-D-Stor Shelving, Vertical 5-Shelf: 72""H x...",665.8800,6,0.00,13.3176
6,25,CA-2015-106320,25/9/2015,30/9/2015,Standard Class,EB-13870,Emily Burns,Consumer,United States,Orem,...,84057,West,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,1044.6300,3,0.00,240.2649
7,28,US-2015-150630,17/9/2015,21/9/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,19140,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.4300,7,0.50,-1665.0522
8,36,CA-2016-117590,8/12/2016,10/12/2016,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,...,75080,Central,TEC-PH-10004977,Technology,Phones,GE 30524EE4,1097.5440,7,0.20,123.4737
9,39,CA-2015-117415,27/12/2015,31/12/2015,Standard Class,SN-20710,Steve Nguyen,Home Office,United States,Houston,...,77041,Central,FUR-BO-10002545,Furniture,Bookcases,"Atlantic Metals Mobile 3-Shelf Bookcases, Cust...",532.3992,3,0.32,-46.9764

In [13]:
df.columns.tolist()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit']

In [14]:
query="""SELECT "Product Name",Sales FROM sales ORDER BY Sales DESC LIMIT 10;"""
result=pd.read_sql(query,conn)
result

                                        Product Name      Sales
0  Cisco TelePresence System EX90 Videoconferenci...  22638.480
1              Canon imageCLASS 2200 Advanced Copier  17499.950
2              Canon imageCLASS 2200 Advanced Copier  13999.960
3              Canon imageCLASS 2200 Advanced Copier  11199.968
4              Canon imageCLASS 2200 Advanced Copier  10499.970
5   GBC Ibimaster 500 Manual ProClick Binding System   9892.740
6               Ibico EPK-21 Electric Binding System   9449.950
7   3D Systems Cube Printer, 2nd Generation, Magenta   9099.930
8  HP Designjet T520 Inkjet Large Format Printer ...   8749.950
9              Canon imageCLASS 2200 Advanced Copier   8399.976

In [15]:
query="""SELECT Category,SUM(Sales) AS Total_Sales FROM sales GROUP BY category ORDER BY Total_Sales DESC;"""
result=pd.read_sql(query,conn)
result

          Category  Total_Sales
0       Technology  836154.0330
1        Furniture  741999.7953
2  Office Supplies  719047.0320

In [16]:
query="""SELECT Category,SUM(Sales) AS Total_Sales FROM sales GROUP BY Category HAVING SUM(Sales)>100000 ORDER BY Total_Sales DESC;"""
result=pd.read_sql(query,conn)
result

          Category  Total_Sales
0       Technology  836154.0330
1        Furniture  741999.7953
2  Office Supplies  719047.0320

In [17]:
customers=df[["Customer ID","Customer Name","Segment"]].drop_duplicates()
customers.to_sql("customers",conn,if_exists="replace",index=False)
print("Customers table created successfully!")

Customers table created successfully!

In [18]:
query = """
SELECT
    s."Customer ID",
    c."Customer Name",
    c.Segment,
    SUM(s.Sales) AS Total_Sales
FROM sales s
JOIN customers c
    ON s."Customer ID" = c."Customer ID"
GROUP BY
    s."Customer ID",
    c."Customer Name",
    c.Segment
ORDER BY Total_Sales DESC
LIMIT 10;
"""

result = pd.read_sql(query, conn)
result

  Customer ID       Customer Name      Segment  Total_Sales
0    SM-20320         Sean Miller  Home Office    25043.050
1    TC-20980        Tamara Chand    Corporate    19052.218
2    RB-19360        Raymond Buch     Consumer    15117.339
3    TA-21385        Tom Ashbrook  Home Office    14595.620
4    AB-10105       Adrian Barton     Consumer    14473.571
5    KL-16645        Ken Lonsdale     Consumer    14175.229
6    SC-20095        Sanjit Chand     Consumer    14142.334
7    HL-15040        Hunter Lopez     Consumer    12873.298
8    SE-20110        Sanjit Engle     Consumer    12209.438
9    CC-12370  Christopher Conant     Consumer    12129.072

In [19]:
query = """
SELECT "Product Name", Sales
FROM sales
WHERE Sales > (
    SELECT AVG(Sales)
    FROM sales
)
ORDER BY Sales DESC
LIMIT 10;
"""

result = pd.read_sql(query, conn)
result

                                        Product Name      Sales
0  Cisco TelePresence System EX90 Videoconferenci...  22638.480
1              Canon imageCLASS 2200 Advanced Copier  17499.950
2              Canon imageCLASS 2200 Advanced Copier  13999.960
3              Canon imageCLASS 2200 Advanced Copier  11199.968
4              Canon imageCLASS 2200 Advanced Copier  10499.970
5   GBC Ibimaster 500 Manual ProClick Binding System   9892.740
6               Ibico EPK-21 Electric Binding System   9449.950
7   3D Systems Cube Printer, 2nd Generation, Magenta   9099.930
8  HP Designjet T520 Inkjet Large Format Printer ...   8749.950
9              Canon imageCLASS 2200 Advanced Copier   8399.976

In [20]:
query = """
WITH category_sales AS (
    SELECT
        Category,
        SUM(Sales) AS Total_Sales
    FROM sales
    GROUP BY Category
)
SELECT
    Category,
    Total_Sales
FROM category_sales
ORDER BY Total_Sales DESC;
"""

result = pd.read_sql(query, conn)
result

          Category  Total_Sales
0       Technology  836154.0330
1        Furniture  741999.7953
2  Office Supplies  719047.0320

In [21]:
query = """
SELECT "Product Name", Sales
FROM sales
WHERE Sales > (
    SELECT AVG(Sales)
    FROM sales
)
ORDER BY Sales DESC
LIMIT 10;
"""

result = pd.read_sql(query, conn)
result

                                        Product Name      Sales
0  Cisco TelePresence System EX90 Videoconferenci...  22638.480
1              Canon imageCLASS 2200 Advanced Copier  17499.950
2              Canon imageCLASS 2200 Advanced Copier  13999.960
3              Canon imageCLASS 2200 Advanced Copier  11199.968
4              Canon imageCLASS 2200 Advanced Copier  10499.970
5   GBC Ibimaster 500 Manual ProClick Binding System   9892.740
6               Ibico EPK-21 Electric Binding System   9449.950
7   3D Systems Cube Printer, 2nd Generation, Magenta   9099.930
8  HP Designjet T520 Inkjet Large Format Printer ...   8749.950
9              Canon imageCLASS 2200 Advanced Copier   8399.976

In [22]:
query = """
SELECT
    "Customer Name",
    Sales,
    RANK() OVER (
        ORDER BY Sales DESC
    ) AS Sales_Rank
FROM sales
LIMIT 10;
"""

result = pd.read_sql(query, conn)
result

        Customer Name      Sales  Sales_Rank
0         Sean Miller  22638.480           1
1        Tamara Chand  17499.950           2
2        Raymond Buch  13999.960           3
3        Tom Ashbrook  11199.968           4
4        Hunter Lopez  10499.970           5
5       Adrian Barton   9892.740           6
6        Sanjit Chand   9449.950           7
7        Bill Shonely   9099.930           8
8        Sanjit Engle   8749.950           9
9  Christopher Conant   8399.976          10

In [23]:
query = """
SELECT
    "Customer Name",
    Sales,
    LAG(Sales) OVER (
        ORDER BY Sales
    ) AS Previous_Sales
FROM sales
LIMIT 10;
"""

result = pd.read_sql(query, conn)
result

      Customer Name  Sales  Previous_Sales
0  Zuschuss Carroll  0.444             NaN
1    Roland Schwarz  0.556           0.444
2       Ken Brennan  0.836           0.556
3     Jas O'Carroll  0.852           0.836
4     Henry Goldwyn  0.876           0.852
5    Craig Molinari  0.898           0.876
6     Mark Van Huff  0.984           0.898
7      Neil Knudson  0.990           0.984
8       Harry Marie  1.044           0.990
9     Tamara Dahlen  1.080           1.044

In [24]:
query = """
SELECT
    "Customer Name",
    Sales,
    LEAD(Sales) OVER (
        ORDER BY Sales
    ) AS Next_Sales
FROM sales
LIMIT 10;
"""

result = pd.read_sql(query, conn)
result

      Customer Name  Sales  Next_Sales
0  Zuschuss Carroll  0.444       0.556
1    Roland Schwarz  0.556       0.836
2       Ken Brennan  0.836       0.852
3     Jas O'Carroll  0.852       0.876
4     Henry Goldwyn  0.876       0.898
5    Craig Molinari  0.898       0.984
6     Mark Van Huff  0.984       0.990
7      Neil Knudson  0.990       1.044
8       Harry Marie  1.044       1.080
9     Tamara Dahlen  1.080       1.080

In [25]:
query = """
CREATE VIEW IF NOT EXISTS category_sales AS
SELECT
    Category,
    SUM(Sales) AS Total_Sales,
    SUM(Profit) AS Total_Profit
FROM sales
GROUP BY Category;
"""

conn.execute(query)
conn.commit()

print("View created successfully!")

View created successfully!

In [26]:
query = """
SELECT *
FROM category_sales
ORDER BY Total_Sales DESC;
"""

result = pd.read_sql(query, conn)
result

          Category  Total_Sales  Total_Profit
0       Technology  836154.0330   145454.9481
1        Furniture  741999.7953    18451.2728
2  Office Supplies  719047.0320   122490.8008

In [27]:
!pip install sqlalchemy

Requirement already satisfied: sqlalchemy in .\anaconda3\Lib\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in .\anaconda3\Lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in .\anaconda3\Lib\site-packages (from sqlalchemy) (4.16.0)

In [28]:
from sqlalchemy import create_engine

engine = create_engine("sqlite:///superstore.db")

print("SQLAlchemy connected successfully!")

SQLAlchemy connected successfully!

In [29]:
query = """
SELECT
    "Product Name",
    SUM(Sales) AS Total_Sales
FROM sales
GROUP BY "Product Name"
ORDER BY Total_Sales DESC
LIMIT 5;
"""

result = pd.read_sql(query, engine)
result

                                        Product Name  Total_Sales
0              Canon imageCLASS 2200 Advanced Copier    61599.824
1  Fellowes PB500 Electric Punch Plastic Comb Bin...    27453.384
2  Cisco TelePresence System EX90 Videoconferenci...    22638.480
3       HON 5400 Series Task Chairs for Big and Tall    21870.576
4         GBC DocuBind TL300 Electric Binding System    19823.479

In [30]:
pd.read_sql(query,engine)

                                        Product Name  Total_Sales
0              Canon imageCLASS 2200 Advanced Copier    61599.824
1  Fellowes PB500 Electric Punch Plastic Comb Bin...    27453.384
2  Cisco TelePresence System EX90 Videoconferenci...    22638.480
3       HON 5400 Series Task Chairs for Big and Tall    21870.576
4         GBC DocuBind TL300 Electric Binding System    19823.479

In [4]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("sqlite:///superstore.db")

print("Pandas and SQLAlchemy are ready!")

Pandas and SQLAlchemy are ready!

In [5]:
query = """
SELECT
    strftime('%Y-%m', "Order Date") AS Month,
    SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Month
ORDER BY Month;
"""

result = pd.read_sql(query, engine)
result

  Month   Total_Sales
0  None  2.297201e+06

In [6]:
query = """
SELECT
    "Customer ID",
    "Customer Name",
    SUM(Sales) AS Total_Spend,
    CASE
        WHEN SUM(Sales) >= 5000 THEN 'High'
        WHEN SUM(Sales) >= 2000 THEN 'Medium'
        ELSE 'Low'
    END AS Spend_Category
FROM sales
GROUP BY "Customer ID", "Customer Name"
ORDER BY Total_Spend DESC;
"""

result = pd.read_sql(query, engine)
result

    Customer ID    Customer Name  Total_Spend Spend_Category
0      SM-20320      Sean Miller    25043.050           High
1      TC-20980     Tamara Chand    19052.218           High
2      RB-19360     Raymond Buch    15117.339           High
3      TA-21385     Tom Ashbrook    14595.620           High
4      AB-10105    Adrian Barton    14473.571           High
..          ...              ...          ...            ...
788    RS-19870       Roy Skaria       22.328            Low
789    MG-18205  Mitch Gastineau       16.739            Low
790    CJ-11875     Carl Jackson       16.520            Low
791    LD-16855     Lela Donovan        5.304            Low
792    TS-21085    Thais Sissman        4.833            Low

[793 rows x 4 columns]

In [7]:
query = """
SELECT
    Region,
    SUM(Sales) AS Total_Sales,
    SUM(Profit) AS Total_Profit
FROM sales
GROUP BY Region
ORDER BY Total_Sales DESC;
"""

result = pd.read_sql(query, engine)
result

    Region  Total_Sales  Total_Profit
0     West  725457.8245   108418.4489
1     East  678781.2400    91522.7800
2  Central  501239.8908    39706.3625
3    South  391721.9050    46749.4303

In [8]:
query = """
SELECT
    Category,
    SUM(Sales) AS Total_Sales,
    SUM(Profit) AS Total_Profit
FROM sales
GROUP BY Category
ORDER BY Total_Profit DESC;
"""

result = pd.read_sql(query, engine)
result

          Category  Total_Sales  Total_Profit
0       Technology  836154.0330   145454.9481
1  Office Supplies  719047.0320   122490.8008
2        Furniture  741999.7953    18451.2728

In [9]:
query = """
SELECT
    "Customer ID",
    "Customer Name",
    SUM(Profit) AS Total_Profit
FROM sales
GROUP BY "Customer ID", "Customer Name"
ORDER BY Total_Profit DESC
LIMIT 10;
"""

result = pd.read_sql(query, engine)
result

  Customer ID         Customer Name  Total_Profit
0    TC-20980          Tamara Chand     8981.3239
1    RB-19360          Raymond Buch     6976.0959
2    SC-20095          Sanjit Chand     5757.4119
3    HL-15040          Hunter Lopez     5622.4292
4    AB-10105         Adrian Barton     5444.8055
5    TA-21385          Tom Ashbrook     4703.7883
6    CM-12385  Christopher Martinez     3899.8904
7    KD-16495         Keith Dawkins     3038.6254
8    AR-10540           Andy Reiter     2884.6208
9    DR-12940         Daniel Raglin     2869.0760

In [10]:
query = """
SELECT
    "Sub-Category",
    SUM(Sales) AS Total_Sales,
    SUM(Profit) AS Total_Profit
FROM sales
GROUP BY "Sub-Category"
ORDER BY Total_Sales DESC
LIMIT 10;
"""

result = pd.read_sql(query, engine)
result

  Sub-Category  Total_Sales  Total_Profit
0       Phones  330007.0540    44515.7306
1       Chairs  328449.1030    26590.1663
2      Storage  223843.6080    21278.8264
3       Tables  206965.5320   -17725.4811
4      Binders  203412.7330    30221.7633
5     Machines  189238.6310     3384.7569
6  Accessories  167380.3180    41936.6357
7      Copiers  149528.0300    55617.8249
8    Bookcases  114879.9963    -3472.5560
9   Appliances  107532.1610    18138.0054

In [11]:
query = """
SELECT
    Region,
    SUM(Sales) AS Total_Sales,
    SUM(Profit) AS Total_Profit,
    ROUND(SUM(Profit) * 100.0 / SUM(Sales), 2) AS Profit_Margin_Percent
FROM sales
GROUP BY Region
ORDER BY Profit_Margin_Percent DESC;
"""

result = pd.read_sql(query, engine)
result

    Region  Total_Sales  Total_Profit  Profit_Margin_Percent
0     West  725457.8245   108418.4489                  14.94
1     East  678781.2400    91522.7800                  13.48
2    South  391721.9050    46749.4303                  11.93
3  Central  501239.8908    39706.3625                   7.92

In [12]:
query = """
SELECT
    "Ship Mode",
    COUNT(*) AS Total_Orders,
    SUM(Sales) AS Total_Sales
FROM sales
GROUP BY "Ship Mode"
ORDER BY Total_Orders DESC;
"""

result = pd.read_sql(query, engine)
result

        Ship Mode  Total_Orders   Total_Sales
0  Standard Class          5968  1.358216e+06
1    Second Class          1945  4.591936e+05
2     First Class          1538  3.514284e+05
3        Same Day           543  1.283631e+05

In [13]:
query = """
SELECT
    State,
    SUM(Sales) AS Total_Sales,
    SUM(Profit) AS Total_Profit
FROM sales
GROUP BY State
ORDER BY Total_Sales DESC
LIMIT 10;
"""

result = pd.read_sql(query, engine)
result

          State  Total_Sales  Total_Profit
0    California  457687.6315    76381.3871
1      New York  310876.2710    74038.5486
2         Texas  170188.0458   -25729.3563
3    Washington  138641.2700    33402.6517
4  Pennsylvania  116511.9140   -15559.9603
5       Florida   89473.7080    -3399.3017
6      Illinois   80166.1010   -12607.8870
7          Ohio   78258.1360   -16971.3766
8      Michigan   76269.6140    24463.1876
9      Virginia   70636.7200    18597.9504